name: Scala CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup GITHUB_USER
      run: export GITHUB_USER=thachi
    - name: Run tests
      run: sbt test publish
