name: Scala CI

on:
  push:
    branches:
      - master

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      env:
        GITHUB_USER: thachi
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt test publish
